### ISSUE TITLE
Input not coming out after Knock Down

### ISSUE THREAD

**Issue by BlazingStarman** [Iquis/rev2-wakeup-tool#14]
I used labryz wake up tool reversal and followed both of your steps which were the same. I hoped yours would work for me, but thats not what happened. It has worked before but now it wont come out after a kd.

**Comment by raisedbyfinches** [comment]
Can you confirm that the recording is in the same slot as the playback? There's going to need to be a bit more info before this can be acted upon I imagine. What's the situation you're trying to replicate? What's the input? Can you post screencaps/recordings showing its use?

**Comment by BlazingStarman** [comment]
https://youtu.be/4-hUy0A7Y6Q
Here's what i did step by step.
The only thing different is that i couldn't find lquis wake up tool anymore so i went by to labreezy's instead.

**Comment by BlazingStarman** [comment]
> Can you confirm that the recording is in the same slot as the playback? There's going to need to be a bit more info before this can be acted upon I imagine. What's the situation you're trying to replicate? What's the input? Can you post screencaps/recordings showing its use?

https://youtu.be/4-hUy0A7Y6Q
Here's what i did step by step.
The only thing different is that i couldn't find lquis wake up tool anymore so i went by to labreezy's instead.
Edit: The input is there and it does come out manually. But not automatically

**Comment by argoneuscze** [comment]
I'm having the same issue, no matter which version I use.

Shows the correct dummy and I can play it back manually, but nothing happens upon wakeup.

EDIT:
This version works fine
https://github.com/Iquis/rev2-wakeup-tool/releases/tag/0.2

**Comment by Iquis** [comment]
It should be fixed with the last release
