### ISSUE TITLE
Unable to get reversals working

### ISSUE THREAD

**Issue by fefo-dev** [Iquis/rev2-wakeup-tool#24]
https://files.catbox.moe/i4mef0.m4v
Replays done manually to show the input injection working. Forgot to show the log for blocks, but it worked fine.

For some reason I can't get reversals with this tool, or Labreezy's version either. The injection works as shown, even for stuff like TK Bad Moon or IAD Tatami, but id never happens as a reversal. Tried running as admin too, no change.

Do you know why this is happening? I don't know how to debug this.

Thanks.

---

I didn't show the setup on video but I went by the recommended steps. The dummy reporting is always accurate.

**Comment by fefo-dev** [comment]
Tested the new release on a clean install from another computer, and the issue persists.

**Comment by fefo-dev** [comment]
https://files.catbox.moe/zkiiiz.m4v
New test done from start on the latest version - same issue. Inputs are injected, the reversal thread recognizes knockdowns, but nothing is played after. What you saw was me mashing the replay button to show the injection working.

**Comment by Iquis** [comment]
Did you set a keyboard key for replay feature in the buttons settings menu?

**Comment by fefo-dev** [comment]
Yes, should I unbind it?

Tested without either record and play bound, same issue.

**Comment by Iquis** [comment]
No. A unique key should be bind

**Comment by Iquis** [comment]
When you press that binded key I suppose the replay is triggered ?

**Comment by fefo-dev** [comment]
Yes, on both videos the replay was me pressing the button. 

Blockstun has the same issue as reported: you can see the reversal thread working on the log, but no reversal ever happens.

**Comment by Iquis** [comment]
I'm working on a new release to trigger the replay with asm injection. 
I was using this method in 0.4.1 version.
Is the replay working with this version?

**Comment by fefo-dev** [comment]
YES, THANK YOU! 0.4.1 worked instantly.

I was going to check older releases to pick up any regression but never did. I'll report back once I test the new release.

If I'm allowed a suggestion: provide a local debug.log for better reporting. Maybe I can understand where tool is failing.

Thanks again, finally I can use it :)

**Comment by Iquis** [comment]
After 0.4.1 I changed how the replay is triggered. The press of the replay key is simulated. 
Before I was using code injection to trigger replay and some people were having problem with this method.
I'll release a new version with both keystroke and injection method and an option to select which one to use

**Comment by starlessand** [comment]
Even with the latest update this is still an issue for me, reversals still never come out.

**Comment by Iquis** [comment]
Did you try version 0.4.1?

**Comment by starlessand** [comment]
Tried it right now and it didn't work for me. The replay gets overridden but never plays on wakeup.

**Comment by Iquis** [comment]
That's weird. Try to run the tool as administrator

**Comment by starlessand** [comment]
Still doesn't work.

**Comment by e-mts** [comment]
Having the same issue
