### ISSUE TITLE
Inputs are injected, actions show on log, but there is no reversal

### ISSUE THREAD

**Issue by fefo-dev** [Iquis/rev2-wakeup-tool#53]
Congrats on the release! The new functions are quite nice even if some (presets) are still in it's infancy. 

But of course reversals don't work for me on Scenario Mode (didn't test/understood Combo enough). As said, the inputs are injected on the replay slot - I can play them manually - log shows all actions that would trigger a replay, along with said replay being "executed", but on either Asm or Keyboard injection nothing happens on my screen.

I'm aware that this is an early release, just keeping you informed if you need any further testing.

Thanks for the continued develoment!

**Comment by Iquis** [comment]
Yup this is a bug I'll fix later
Make sure the "Play button" is mapped to a letter on your keyboard
https://twitter.com/iquisiquis/status/1630529997742981121?s=20

**Comment by fefo-dev** [comment]
Thanks, I'll keep waiting.

I'll remap the replay button to other keys, I had issues before with numpad keys on games/tools.
