### ISSUE TITLE
Reversal doesn't come out if you use RC

### ISSUE THREAD

**Issue by e-mts** [Iquis/rev2-wakeup-tool#66]
I'm not sure whether this is an issue but, reversals don't come out frame 1 if you RC. As an example, I'm trying to lab Ky's 2D into CSE YRC, the reversal works fine frame 1 if you don't YRC, but it messes up with any kind of RC and they get hit, is it possible to fix this or is there a workaround?

[Video about the issue.](https://streamable.com/smi59p)

**Comment by fishingmachine1** [comment]
late but just so you know, RC eats the other persons input if its done on the same frame, so reversals wouldnt work frame 1 if you yrc right when they reversal.

**Comment by e-mts** [comment]
I know but if it's possible to read the game state for a YRC then you would be able to send the input again after the freeze ends 

> late but just so you know, RC eats the other persons input if its done on the same frame, so reversals wouldnt work frame 1 if you yrc right when they reversal.

**Comment by worsety** [comment]
Implemented in 1.2.1, can probably be closed as fixed if nobody has further issues with this?
