### ISSUE TITLE
Wake-up Tool programs replay slot but does not execute on wake-up

### ISSUE THREAD

**Issue by OOPMan** [Iquis/rev2-wakeup-tool#77]
Hi there, I'm trying to use the wake-up tool but running into some weird behaviour.

The tool seems to succeed at programming the replay slot and based on the log it looks like it's detecting the wake-up event but in the game the dummy doesn't actually execute the specified commands :-/

![image](https://github.com/Iquis/rev2-wakeup-tool/assets/248980/977e69c4-a07d-42c6-871e-52b628fe14ef)
![image](https://github.com/Iquis/rev2-wakeup-tool/assets/248980/4fdd8a51-849e-47ab-99ce-dfc9774252f1)

I can test the programmed inputs using my Play Recording binding but no luck on the wake-up. I've tried running both as Administrator and as my normal user, also tried the various other When options but no dice.

Any ideas what the issue could be?

EDIT: Forgot to mention, the tool is using Asm injection. Could there be an issue due to me having two controllers plugged in?

**Comment by Iquis** [comment]
Two controllers plugged in can be a problem.
Make sure you use the controller marked as P1 when you enter training mode.

You can also try to use Keyboard stroke configuration and map the replay feature to a key

**Comment by OOPMan** [comment]
@Iquis Disconnecting my second controller fixed the issue. Thanks for the suggestion!
